"""
Django settings for gmugrader project.

Generated by 'django-admin startproject' using Django 1.9.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&k$$%(h$#hn7uq61*xyn38)hchj(k7n5^8w^=sbbcy@^obmdh&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'fileuploader.apps.FileuploaderConfig',
    'polls.apps.PollsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #'fileuploader',
    'tinymce',
    'datetimewidget',
    'bootstrap3',
    'django_extensions'
]

GRAPH_MODELS = {
  'all_applications': True,
  'group_models': True,
}

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'dmgradermailer@gmail.com'
EMAIL_HOST_PASSWORD = 'bG9uZyBzdHJpbmcgaGVyZQ'
EMAIL_PORT = 587


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)




ROOT_URLCONF = 'gmugrader.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gmugrader.wsgi.application'



# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }


# settings.py
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'HOST': 'db', # set in docker-compose.yml
        'PORT': 5432 # default postgres port
    }
}




#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql_psycopg2',
#        'NAME': 'gmugrader',
#        'USER': 'abc',
#        'PASSWORD': '123',
#        'HOST': '0.0.0.0',
#        'PORT': '',
#    }
#}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

#MEDIA_ROOT='/files/'
#MEDIA_ROOT='~/dmgrader/gradingwebapp/files/'

MEDIA_ROOT='/Users/huzefa/new-dm/dmgrader/gradingwebapp/files/'



MEDIA_URL = '/files/'

APPEND_SLASH = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
# 
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "fileuploader/static"),
)

STATIC_URL = '/static/'

STATIC_URL = '/fileuploader/static/'

STATIC_ROOT = '/fileuploader/static/'
LOGIN_URL = '/fileuploader/login/'

#LOGIN_REDIRECT_URL = ('..')
#CKEDITOR_UPLOAD_PATH = MEDIA_ROOT
#CKEDITOR_BASEPATH = os.path.join(STATIC_ROOT, "ckeditor/")


TINYMCE_DEFAULT_CONFIG = {
        'plugins': "table,spellchecker,paste,searchreplace",
        'theme': "advanced",
}
TINYMCE_SPELLCHECKER = True
#TINYMCE_COMPRESSOR = True


USE_TZ=True
TIME_ZONE='America/New_York'

