# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-18 14:04
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fileuploader.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('fileshot', models.FileField(upload_to=fileuploader.models.get_upload_file_name)),
                ('accuracy', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ground_truth', models.FileField(upload_to=fileuploader.models.get_upload_file_name)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date  published')),
                ('deadline_date', models.DateTimeField(blank=True, verbose_name='deadline')),
                ('uploaded_cnt', models.IntegerField(default=0)),
                ('train_data', models.FileField(blank=True, null=True, upload_to=fileuploader.models.get_upload_file_name)),
                ('test_data', models.FileField(blank=True, null=True, upload_to=fileuploader.models.get_upload_file_name)),
                ('format_example', models.FileField(blank=True, null=True, upload_to=fileuploader.models.get_upload_file_name)),
                ('sampling_private', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_file', models.FileField(upload_to=fileuploader.models.get_upload_file_name)),
                ('attempt', models.IntegerField(default=0)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('-1'), max_digits=5)),
                ('submission_time', models.DateTimeField(auto_now_add=True, verbose_name='date submitted')),
                ('status', models.CharField(choices=[('ER', 'Error'), ('OK', 'Okay')], default='ER', max_length=2)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileuploader.Assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_attempts', models.IntegerField(default=0)),
                ('team_name', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
