# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-12 17:58
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import fileuploader.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileuploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classnum', models.CharField(choices=[('NONE', 'NONE'), ('584', '584'), ('484', '484')], default='NONE', max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='assignment',
            name='class_name',
            field=models.CharField(default='NONE', max_length=5),
        ),
        migrations.AddField(
            model_name='assignment',
            name='hidden_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assignment',
            name='num_subs_per_day',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='assignment',
            name='scoring_method',
            field=models.CharField(choices=[('AC', 'Accuracy'), ('F1', 'F1-Score'), ('V1', 'V-measure'), ('RE', 'rmse'), ('RC', 'RC'), ('OT', 'Other')], default='AC', max_length=2),
        ),
        migrations.AddField(
            model_name='solution',
            name='public_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('-1'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='format_example',
            field=models.FileField(default=datetime.datetime(2018, 10, 12, 17, 58, 43, 620364, tzinfo=utc), upload_to=fileuploader.models.get_upload_file_name),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='test_data',
            field=models.FileField(upload_to=fileuploader.models.get_upload_file_name),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='train_data',
            field=models.FileField(upload_to=fileuploader.models.get_upload_file_name),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
