# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploader', '0002_auto_20160108_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='accuracy',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=7),
            preserve_default=False,
        ),
    ]
