# Generated by Django 2.1.5 on 2019-02-22 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploader', '0002_auto_20181012_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Winter', 'Winter'), ('Fall', 'Fall')], default='Fall', max_length=6),
        ),
        migrations.AddField(
            model_name='class',
            name='year',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='class',
            name='classnum',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='class',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
