# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 21:26
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploader', '0003_article_accuracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='accuracy',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7),
        ),
    ]
