# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploader', '0005_assignment_solution_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='ground_truth',
        ),
    ]
