# Generated by Django 2.1.5 on 2019-03-29 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploader', '0006_auto_20190329_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='class_name',
        ),
    ]
