# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-19 14:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import fileuploader.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploader', '0006_remove_assignment_ground_truth'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='ground_truth',
            field=models.FileField(default=datetime.datetime(2016, 4, 19, 14, 41, 1, 454283, tzinfo=utc), upload_to=fileuploader.models.get_upload_file_name),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
