# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-25 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploader', '0007_auto_20160419_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date  published'),
        ),
    ]
