# Generated by Django 2.1.5 on 2019-03-29 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileuploader', '0007_remove_assignment_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('enrolled_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='date  enrolled')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileuploader.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
